version: '3'

services:
  db:
    image: postgres:10
    ports:
      - '5432:5432'
    # volumes:
    #   -  ./postgres-data:/var/lib/postgresql/data
    environment:
      DEBUG: 'false'
      POSTGRES_USER: postgres
      POSTGRES_PASS:
      POSTGRES_DB: database_development_shop
    expose:
      - "5432"
  api:
    build:
      context: ./services
      dockerfile: ./api/Dockerfile
    image: backend/api
    links:
      - user
    ports:
      - 3000:3000
  user:
    build:
      context: ./services
      dockerfile: ./user/Dockerfile
    image: backend/user
    links:
      - db
    ports:
      - 50050:50050
    depends_on:
      - db
    command: ["./wait-for-it.sh", "node", "app.js"]
    environment:
      PORT: 80
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      DB_NAME: user
      DB_HOST: db
