version: '3'

services:
  db:
    image: postgres:10
    ports:
      - '5432:5432'
    volumes:
      -  ./postgres-data:/var/lib/postgresql/data
    environment:
      DEBUG: 'false'
      POSTGRES_USER: scastro81
      POSTGRES_PASS:
      POSTGRES_NAME: database_development_shop
  api:
    build:
      context: ./services
      dockerfile: ./api/Dockerfile
    image: backend/api
    links:
      - user
    ports:
      - "3000:3000"
    # volumes:
    #   - /var/lib/app
  user:
    build:
      context: ./services
      dockerfile: ./user/Dockerfile
    image: backend/user
    links:
      - db
    ports:
      - '50050:50050'
    # volumes:
    #   - /var/lib/app
    depends_on:
      - db
    environment:
      POSTGRES_USER: scastro81
      POSTGRES_PASSWORD:
      POSTGRES_DB: database_development_shop
      POSTGRES_HOST: db

volumes:
  postgres-data:
